name: Build and Deploy Docker 
on:
  push: 
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: self-hosted  
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore Packages
        shell: cmd
        run: nuget restore TestCICDDocker.sln

      - name: Build Solution
        shell: cmd
        run: |
          msbuild.exe TestCICDDocker.sln /p:platform="Any CPU" /p:configuration="Release" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true 
    
      - name : Prepare Docker Context
        shell: cmd
        run: |
          mkdir TestPublish
          xcopy /s /e /y ".\TestCICDDocker\obj\Release\Package\PackageTmp\*" ".\TestPublish"
        
      - name: Log in to GHCR 
        shell: cmd
        run: echo %GHCR_TOKEN% | docker login ghcr.io -u %GITHUB_ACTOR% --password-stdin
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
      
      - name: Build Docker Image
        shell: cmd
        run: docker build -t testcicddocker:latest -f .\TestCICDDocker\TestCICDDocker\TestCICDDocker\Dockerfile .\TestCICDDocker\TestPublish
      
      - name: Tag & Push to GHCR
        shell: cmd
        run: |
          docker tag servicefactory:latest ghcr.io/phucnh294/testcicddocker:latest
          docker push ghcr.io/phucnh294/TestCICDDocker:latest
      
      
