name: SF - Build and Deploy Docker 
on:
  push: 
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: self-hosted  
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore Packages
        shell: cmd
        run: nuget restore TestCICDDocker.sln

      - name: Build Solution
        shell: cmd
        run: |
          msbuild.exe TestCICDDocker.sln /p:platform="Any CPU" /p:configuration="Release" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true 
      
      - name: Log in to GHCR
        shell: pwsh
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u {{ github.actor }} --password-stdin
      
      - name: Build Docker Image
        shell: pwsh
        run: docker build -t testcicddocker:latest .
      
      - name: Tag & Push to GHCR
        shell: pwsh
        run: |
          docker tag servicefactory:latest ghcr.io/phucnh294/testcicddocker:latest
          docker push ghcr.io/phucnh294/TestCICDDocker:latest
      
      
